name: FANS-Dev

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: FANS-React-Dev
    ports:
      - "5173:5173"
    volumes:
      - /${PWD}/frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: FANTS-FastAPI-Dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
